import { atom } from "recoil";
import { recoilPersist } from "recoil-persist";

const { persistAtom } = recoilPersist({
  key: "recoil-persist",
  storage: localStorage,
});

export const recGenreState = atom<Array<string>>({
  key: "recGenreState",
  default: [],
});

export const recResultState = atom<Array<Object>>({
  key: "recResultState",
  default: [
    {
      pk: 1,
      title: "더 글로리",
      runtime: 1,
      rate: 4.5,
      img_path: "https//:abc.def.com",
      type: "드라마",
      season: 1,
      finalEpisode: 5,
      ott: "netflix",
      genres: ["드라마", "학교"],
      isWish: false,
    },
    {
      pk: 2,
      title: "트와일라잇",
      runtime: 3,
      rate: 3.7,
      img_path: "https//:abc.def.com",
      type: "영화",
      season: 1,
      finalEpisode: 1,
      ott: "wavve",
      genres: ["야생", "뱀파이어"],
      isWish: true,
    },
    {
      pk: 3,
      title: "박물관이 살아있다 : Walking Moving Museum",
      runtime: 8,
      rate: 1.2,
      img_path: "https//:abc.def.com",
      type: "영화",
      season: 1,
      finalEpisode: 1,
      ott: "wavve",
      genres: ["박물관", "리얼리티"],
      isWish: false,
    },
    {
      pk: 4,
      title: "박물관이 살아있다 : Walking Moving Museum",
      runtime: 8,
      rate: 1.2,
      img_path: "https//:abc.def.com",
      type: "영화",
      season: 1,
      finalEpisode: 1,
      ott: "wavve",
      genres: ["박물관", "리얼리티"],
      isWish: false,
    },
    {
      pk: 5,
      title: "박물관이 살아있다 : Walking Moving Museum",
      runtime: 8,
      rate: 1.2,
      img_path: "https//:abc.def.com",
      type: "영화",
      season: 1,
      finalEpisode: 1,
      ott: "wavve",
      genres: ["박물관", "리얼리티"],
      isWish: false,
    },
    {
      pk: 6,
      title: "박물관이 살아있다 : Walking Moving Museum",
      runtime: 8,
      rate: 1.2,
      img_path: "https//:abc.def.com",
      type: "영화",
      season: 1,
      finalEpisode: 1,
      ott: "wavve",
      genres: ["박물관", "리얼리티"],
      isWish: false,
    },
    {
      pk: 7,
      title: "박물관이 살아있다 : Walking Moving Museum",
      runtime: 8,
      rate: 1.2,
      img_path: "https//:abc.def.com",
      type: "영화",
      season: 1,
      finalEpisode: 1,
      ott: "wavve",
      genres: ["박물관", "리얼리티"],
      isWish: false,
    },
    {
      pk: 8,
      title: "박물관이 살아있다 : Walking Moving Museum",
      runtime: 8,
      rate: 1.2,
      img_path: "https//:abc.def.com",
      type: "영화",
      season: 1,
      finalEpisode: 1,
      ott: "wavve",
      genres: ["박물관", "리얼리티"],
      isWish: false,
    },
  ],
  effects_UNSTABLE: [persistAtom],
});
