import { atom } from "recoil";
import { schedule } from "interface/schedule";

export const weekScheduleState = atom<schedule>({
  key: "weekScheduleState",
  default: {
    0: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        img_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        isWish: false,
        isLike: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
      },
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    1: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        img_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        isWish: false,
        isLike: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
      },
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    2: [],
    3: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    4: [],
    5: [],
    6: [],
  },
});

export const monthScheduleState = atom<schedule>({
  key: "monthScheduleState",
  default: {
    1: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    2: [],
    3: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    4: [],
    5: [],
    6: [],
    7: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    8: [],
    9: [],
    10: [],
    11: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    12: [],
    13: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        img_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        isWish: false,
        isLike: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
      },
    ],
    14: [],
    15: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        img_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        isWish: false,
        isLike: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
      },
    ],
    16: [],
    17: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    18: [],
    19: [],
    20: [],
    21: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        img_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        isWish: false,
        isLike: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
      },
    ],
    22: [],
    23: [],
    24: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        img_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        isWish: false,
        isLike: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
      },
    ],
    25: [],
    26: [],
    27: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
    ],
    28: [],
    29: [],
    30: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        img_path: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        isWish: true,
        isLike: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
      },
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        img_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdrop_path: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        isWish: false,
        isLike: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
      },
    ],
    31: [],
  },
});
