import { atom } from "recoil";
import { recoilPersist } from "recoil-persist";
import { schedule, ScheduleAll } from "interface/schedule";

const { persistAtom } = recoilPersist({
  key: "recoil-persist",
  storage: localStorage,
});

export const weekScheduleState = atom<schedule>({
  key: "weekScheduleState",
  default: {
    0: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        imgPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        episode: 5,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        wish: false,
        like: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    1: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        imgPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        episode: 6,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        wish: false,
        like: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    2: [],
    3: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    4: [],
    5: [],
    6: [],
  },
});

export const monthScheduleState = atom<schedule>({
  key: "monthScheduleState",
  default: {
    1: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    3: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    7: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    11: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    13: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        imgPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        episode: 5,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        wish: false,
        like: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    15: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        imgPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        episode: 6,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        wish: false,
        like: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    17: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    21: [
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        imgPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        episode: 7,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        wish: false,
        like: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    24: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        imgPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        episode: 8,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        wish: false,
        like: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    27: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
    30: [
      {
        pk: 2,
        title: "트와일라잇",
        runtime: 60,
        rate: 3.7,
        imgPath: "https://images.justwatch.com/poster/129382738/s592/twilight.webp",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "영화",
        season: 0,
        finalEpisode: 0,
        episode: 0,
        ott: {
          wavve: "https://www.wavve.com/player/movie?movieid=MV_LO01_LO0000000038",
          watcha: "https://watcha.com/contents/myWqyBW",
        },
        genres: ["야생", "뱀파이어"],
        wish: true,
        like: -1,
        summarize: "뱀파이어가 울부지저따. 뱀파이어는 짱 쎄따. 크와아앙",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
      {
        pk: 1,
        title: "더 글로리",
        runtime: 50,
        rate: 4.5,
        imgPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        backdropPath: "https://images.justwatch.com/poster/302518136/s592/시즌-1",
        type: "드라마",
        season: 1,
        finalEpisode: 10,
        episode: 9,
        ott: { netflix: "https://www.netflix.com/kr/title/81519223" },
        genres: ["드라마"],
        wish: false,
        like: 1,
        summarize:
          "어느 날 길을 걷던 걸무고는 우연히 알 수 없는 동전을 줍게 되고, 이 동전의 충격적인 정체가 알려지며 사건에 휩싸이게 되는데... 과연 걸무고는 무사할 수 있을까?",
        audienceAge: 15,
        date: "2023-05-18",
        view: false,
      },
    ],
  },
});

export const scheduleAllState = atom<ScheduleAll>({
  key: "scheduleAllState",
  default: {},
  effects_UNSTABLE: [persistAtom],
});
