# Generated by Django 3.2.13 on 2023-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.TextField()),
                ('is_view', models.TextField()),
                ('view_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audience_age', models.IntegerField()),
                ('final_episode', models.IntegerField(blank=True, null=True)),
                ('horizontial_img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.FloatField()),
                ('release_date', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField()),
                ('season', models.IntegerField(blank=True, null=True)),
                ('summarize', models.CharField(blank=True, max_length=5000, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'content_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contentott',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contentott',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField()),
                ('is_like', models.BooleanField()),
            ],
            options={
                'db_table': 'like_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ott',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurnContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('episode', models.IntegerField()),
            ],
            options={
                'db_table': 'turn_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.TextField()),
                ('img_name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_content_alarm', models.TextField()),
                ('is_deleted', models.TextField()),
                ('is_ott_alarm', models.TextField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'user_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userott',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.TextField()),
            ],
            options={
                'db_table': 'userott',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.TextField()),
            ],
            options={
                'db_table': 'wish_content',
                'managed': False,
            },
        ),
    ]
