# Generated by Django 4.2.1 on 2023-05-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.TextField()),
                ('is_view', models.TextField()),
                ('view_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audience_age', models.IntegerField()),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('final_episode', models.IntegerField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.FloatField()),
                ('release_date', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField()),
                ('season', models.IntegerField(blank=True, null=True)),
                ('summarize', models.CharField(blank=True, max_length=5000, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('popularity', models.IntegerField()),
            ],
            options={
                'db_table': 'content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'content_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contentott',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ott_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'contentott',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.TextField()),
                ('like', models.FloatField(blank=True, null=True)),
                ('is_like', models.TextField()),
            ],
            options={
                'db_table': 'like_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ott',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ranking_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleShare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule_share',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurnContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('episode', models.IntegerField()),
            ],
            options={
                'db_table': 'turn_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.TextField()),
                ('img_name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_content_alarm', models.TextField()),
                ('is_deleted', models.TextField()),
                ('is_ott_alarm', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'user_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userott',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('end', models.DateField(blank=True, null=True)),
                ('is_deleted', models.TextField()),
                ('is_overed', models.TextField()),
                ('start', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userott',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserViewingStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_viewing_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.TextField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wish_content',
                'managed': False,
            },
        ),
    ]
