apiVersion: apps/v1
kind: Deployment
metadata:
 name: ai-service
 labels:
   app: ai-service
spec:
 replicas: 2
 selector:
   matchLabels:
     app: ai-service
 template:
   metadata:
     labels:
       app: ai-service
   spec:
     containers:
       - name: ai-service
         image: docker.io/runtogether/watchify:ai299
     imagePullSecrets:
       - name: dockerhub
         ports:
           - containerPort: 8100
         env:
           - name: DB_HOST
             valueFrom:
               secretKeyRef:
                 name: db-secret
                 key: DB_HOST
           - name: DB_PORT
             valueFrom:
               secretKeyRef:
                 name: db-secret
                 key: DB_PORT
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 name: db-secret
                 key: DB_NAME
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                 name: db-secret
                 key: DB_USER
           - name: DB_Password
             valueFrom:
               secretKeyRef:
                 name: db-secret
                 key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
 name: ai-service
spec:
 type: ClusterIP
 selector:
   app: ai-service
 ports:
   - protocol: TCP
     port: 8100
