apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-service
  labels:
    app: back-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-service
  template:
    metadata:
      labels:
        app: back-service
    spec:
      containers:
        - name: back-service
          image: docker.io/runtogether/watchify:backend157
      imagePullSecrets:
        - name: dockerhub
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: watchifydb.cph3uafcff1h.ap-northeast-2.rds.amazonaws.com
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: sins
            - name: DB_USER
              value: watchifyadmin
            - name: DB_Password
              value: qudwlsgoa
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: ClusterIP
  selector:
    app: back-service
  ports:
    - protocol: TCP
      port: 8000
