apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-service
  namespace: elastic # elastic 네임스페이스에 속하도록 수정
  labels:
    app: elastic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-service
  template:
    metadata:
      labels:
        app: elastic-service
    spec:
      containers:
      - name: elastic-service
        image: docker.io/runtogether/watchify:elastic
        imagePullSecrets:
          - name: dockerhub

        #  env:
        # - name: discovery.type
        #   value: "single-node"
        ports:
        - containerPort: 9200
        - containerPort: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  namespace: elastic # elastic 네임스페이스에 속하도록 수정
spec:
  type: ClusterIP
  ports:
  - name: elasti-rest
    port: 9200
    protocol: TCP
    targetPort: 9200
